name: Release

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Login to the Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for the latest stable version of BYOND
        id: stable-version-check
        run: |
          echo "⏳ Checking for the latest stable version of BYOND..."
          BYOND_VERSION="$(sed -n 1p <(curl https://secure.byond.com/download/version.txt))"
          BYOND_MAJOR_VERSION="$(echo "$(cut -d '.' -f 1 <(echo "$BYOND_VERSION"))")"
          BYOND_MINOR_VERSION="$(echo "$(cut -d '.' -f 2 <(echo "$BYOND_VERSION"))")"
          echo "BYOND_VERSION="$BYOND_VERSION"" >> $GITHUB_OUTPUT
          echo "BYOND_MAJOR_VERSION="$BYOND_MAJOR_VERSION"" >> $GITHUB_OUTPUT
          echo "BYOND_MINOR_VERSION="$BYOND_MINOR_VERSION"" >> $GITHUB_OUTPUT
          echo "✔️ The latest stable version of BYOND: ${BYOND_VERSION}"
      
      - name: Check for stable linux release binaries
        id: stable-binaries-check
        continue-on-error: true
        env:
          BYOND_VERSION: ${{ steps.stable-version-check.outputs.BYOND_VERSION }}
          BYOND_MAJOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MAJOR_VERSION }}
          BYOND_MINOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MINOR_VERSION }}
        run: |
          echo "⏳ Checking for stable linux release binaries..."
          RESPONSE=$(curl --head --silent "http://www.byond.com/download/build/${BYOND_MAJOR_VERSION}/${BYOND_MAJOR_VERSION}.${BYOND_MINOR_VERSION}_byond_linux.zip" | head -n1 | cut -d ' ' -f 2)
          RESPONSE=$(($RESPONSE))

          if [ $RESPONSE -eq 200 ]; then
            echo "✔️ Stable linux release binaries were found for BYOND version: ${BYOND_VERSION}"
          else
            echo "❌ Stable linux release binaries could not be found for BYOND version: ${BYOND_VERSION}"
            exit $RESPONSE
          fi
      
      - name: Check if the stable release was already published to the Docker Registry
        id: stable-release-check
        continue-on-error: true
        env:
          BYOND_VERSION: ${{ steps.stable-version-check.outputs.BYOND_VERSION }}
          BYOND_MAJOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MAJOR_VERSION }}
          BYOND_MINOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MINOR_VERSION }}
        run: |
          echo "⏳ Checking if the stable release was already published to the Docker Registry..."
          docker manifest inspect ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_VERSION }}
          if [ $? -eq 0 ]; then
            echo "✔️ An existing tag was found! A new docker image will not be built."
          else
            echo "❌ An existing tag was not found."
          fi
      
      - name: Build the stable Docker image and publish to the Docker Registry
        uses: docker/build-push-action@v5
        if: ${{ steps.stable-binaries-check.outcome == 'success' && steps.stable-release-check.outcome == 'failure' }}
        env:
          BYOND_VERSION: ${{ steps.stable-version-check.outputs.BYOND_VERSION }}
          BYOND_MAJOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MAJOR_VERSION }}
          BYOND_MINOR_VERSION: ${{ steps.stable-version-check.outputs.BYOND_MINOR_VERSION }}
        with:
          context: .
          push: true
          build-args: |
            BYOND_MAJOR=${{ env.BYOND_MAJOR_VERSION }}
            BYOND_MINOR=${{ env.BYOND_MINOR_VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_VERSION }}
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BYOND_MAJOR_VERSION }}
            ${{ env.REGISTRY }}/${{ github.repository }}:latest